### ISSUE TITLE
Wiggler Radiation from constant magnetic field

### ISSUE THREAD

**Issue by jureyherrera** [oasys-kit/XOPPY#102]
**Wiggler Radiation** widget is not working for the constant magnetic field option **_Bending magnet (cte B)_**. After some tests, the easiest way to fix it is just by changing the function **create_magnetic_field_for_bending_magnet** from the XOPPY tools:
https://github.com/oasys-kit/XOPPY/blob/4a8dcdbc36351e707d5be2387b2e730b83a58cf5/orangecontrib/xoppy/util/xoppy_bm_wiggler.py#L521
Proposed change: `Lmax = numpy.abs(L * 1.0)`

**Comment by srio** [comment]
Done for the next version. Thanks!
