### ISSUE TITLE
Import in the test

### ISSUE THREAD

**Issue by jureyherrera** [oasys-kit/XOPPY#109]
It is needed, not urgent, to change the **import** in the **test part** of the following XOPPY widgets: 

-  Power: https://github.com/oasys-kit/XOPPY/blob/eb89cd49f97b521ec5f48e7269c8755dfa76335e/orangecontrib/xoppy/widgets/optics/xpower.py#L1020
- 3D Power: https://github.com/oasys-kit/XOPPY/blob/eb89cd49f97b521ec5f48e7269c8755dfa76335e/orangecontrib/xoppy/widgets/optics/power3Dcomponent.py#L925

Cheers, J

**Comment by lucarebuffi** [comment]
Done, thank you for reporting it
