### ISSUE TITLE
Flux units in widget: Aperture Flux TC

### ISSUE THREAD

**Issue by jureyherrera** [oasys-kit/XOPPY#110]
Hello,
There is an error in the Flux units from the Aperture Flux TC widget: 
https://github.com/oasys-kit/XOPPY/blob/4263d02cde69f0e774a6673e994ff0e5191c86d8/orangecontrib/xoppy/widgets/source/xtcap.py#L552

Thank you for your attention, J

**Comment by srio** [comment]
Do you mean "Flux (ph/s/mm^2/0.1%bw)" should say "Flux (ph/s/0.1%bw)" ?

**Comment by jureyherrera** [comment]
Yes, but I closed this issue because I the end I was not sure
