### ISSUE TITLE
gfortran issues on OSX

### ISSUE THREAD

**Issue by maltissimo** [oasys-kit/XOPPY#73]
Hi, 

there seem to be a missing gfortran component on the distribution. Please see the attached image.  
<img width="953" alt="Screenshot 2019-05-14 at 14 01 00" src="https://user-images.githubusercontent.com/41440861/57696692-ad187300-7651-11e9-91ec-ac53ec0dec96.png">

I did install gfortran on my system, but it doesn't seem to help.

**Comment by srio** [comment]
This problem is referred here: 
https://github.com/oasys-kit/XOPPY/issues/66
