### ISSUE TITLE
3D Power widget - Not working when using different density

### ISSUE THREAD

**Issue by jureyherrera** [oasys-kit/XOPPY#75]
The widget 3D Power is not working when a different density is given. For instance, in the case of CVD Diamond window (**C** element) it works fine for the preset density (density box=**?**), but when the density value is changed (e.g. 3.51 g/cm^3), the widget doesn't works and sends an error with the message: _'float' object has no attribute 'strip'_ 

![3D_power_strip_error](https://user-images.githubusercontent.com/31166917/68661928-14997780-053c-11ea-8d96-d8918a11559e.png)

Thank you in advance and sorry for any inconvenience.

**Comment by srio** [comment]
This widget has been completely rewritten. It is called now power3Dcomponent. It accepts only one element, but you can chain different widgets. I hope this problem is solved.

**Comment by jureyherrera** [comment]
This issue is fixed and new widget is working perfectly fine, including the very interesting new features. Thank you very much.
