### ISSUE TITLE
TC-Slit not working

### ISSUE THREAD

**Issue by pbrumund-73** [oasys-kit/XOPPY#76]
The TC-slit widget in the oasys canvas does not work anymore.

Error: 'gapHcenter' (see picture below)

It appears the _xoppy_undulators.py_ and _srundplug.py_ have been extended by the possibility to position the mask centre. This seems to have not been added to the TC-slit widget.

Apparently a new widget _aperture flux TC_ (much faster...?) has been added. What is the function to be called with a python code?

![TC-Slit error](https://user-images.githubusercontent.com/59114255/71785856-f3697a80-3004-11ea-8ae7-77821566a439.png)

**Comment by srio** [comment]
Fixed.
