### ISSUE TITLE
Xcrystal error"No such file or directory" when acquiring Enery scan data 

### ISSUE THREAD

**Issue by shadow19820714** [oasys-kit/XOPPY#77]
Hi， the calculation of Xcrystal widget can't be implemented  when the  Energy scan was choosen. Pls find attached error report.  
![Xcrystal eror](https://user-images.githubusercontent.com/10190382/76822677-c16a6500-684c-11ea-8fbc-f2df3cd7bebe.JPG)

**Comment by srio** [comment]
The "Fix Value E or Theta"  is the energy when you do an angle scan, but it must be set to the Bragg angle when you do an energy scan:

![image](https://user-images.githubusercontent.com/502315/77366960-6639e600-6d16-11ea-8faf-ce14194b6968.png)

**Comment by shadow19820714** [comment]
hi Srio， I forgot to change the FIx value when I catch  the screen. Actually ,  the error is still reported when the mamxium scan value set to a large number, like 15000 eV

**Comment by srio** [comment]
If you want an energy with an impossible Bragg angle the code comes to exceptions and there is no output. May be that is the problem...

**Comment by shadow19820714** [comment]
ok~，  really appreciate~
