### ISSUE TITLE
No such file or directory: 'diff_pat.par'

### ISSUE THREAD

**Issue by amicitas** [oasys-kit/XOPPY#85]
I am trying to run XOPPY through OASYS and I am getting the following error:

    [Errno 2] No such file or directory: 'diff_pat.par'

I had performed the same calculation successfully 2 weeks ago, (last time I tried was Sep 25th).  As far as I know I have not changed anything in my configuration. However, I have reinstalled OASYS several times in the meantime.

OASYS 1.2
XOPPY 1.0.92
Mac OS X 10.14.6

![image](https://user-images.githubusercontent.com/228288/95471415-ebea4f80-094f-11eb-9943-f5ef82f63b4a.png)

**Comment by srio** [comment]
Hi, 
could you please: 
1) open a terminal window
2 ) cd /Volumes/DataHD.....oasys 
3) /Applicat.....< xoppy.inp
and tell me what it says? 

thanks!

**Comment by amicitas** [comment]
The relevant part is:

    dyld: Library not loaded: /usr/local/gfortran/lib/libquadmath.0.dylib

Here is the full output from my terminal:

```
npablant-lt:oasys $cd /u/npablant/temp/oasys
npablant-lt:oasys $ls
xcrystal.bra  xoppy.inp
npablant-lt:oasys $/Applications/Oasys1.2.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangecontrib/xoppy/util/bin/darwin/diff_pat' < xoppy.inp
> 
npablant-lt:oasys $'/Applications/Oasys1.2.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangecontrib/xoppy/util/bin/darwin/diff_pat' < xoppy.inp
dyld: Library not loaded: /usr/local/gfortran/lib/libquadmath.0.dylib
  Referenced from: /Applications/Oasys1.2.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangecontrib/xoppy/util/bin/darwin/diff_pat
  Reason: image not found
Abort trap: 6
npablant-lt:oasys $
```

**Comment by srio** [comment]
Hello, 
there is a problem with the dynamic libraries used in compiled fortran codes. I thought this was fixed. 

I recompiled a few of them. Try to upgrade the xoppy version (to 1.0.93) and try again. 

Let me know if there are still problems. If not, please close the issue. 

Regards, 
Manuel

**Comment by amicitas** [comment]
Dear Manuel,

I upgraded to XOPPY 1.0.93 and it is now working for me again.  Thank you for the quick fix!

Sincerely,
Novimir Pablant
