### ISSUE TITLE
Visualitation of flux plot on widget (vertical axis)

### ISSUE THREAD

**Issue by jureyherrera** [oasys-kit/XOPPY#86]
Dear Manolo,
It appears that something got lost during an upgrade, because now the scientific notation is missing in the plots, specifically in the ordinates of the XOPPY widgets that shows flux plots. Since normally the orders of magnitude of the flux are enormous, nor god can read them now ;-). We would appreciate if you fix this issue.

Examples:
Undulator spectrum:
![image](https://user-images.githubusercontent.com/31166917/96153826-6d248200-0f0e-11eb-94b1-a073119fa65e.png)
TC-Slits:
![image](https://user-images.githubusercontent.com/31166917/96154241-e2905280-0f0e-11eb-8be9-aab93b821ccc.png)

Best regards, J

**Comment by lucarebuffi** [comment]
Please update OASYS. It should be fixed.

**Comment by jureyherrera** [comment]
Thanks a lot Luca, kind regards, J.
